name: flutter_snowboy_example
description: Demonstrates how to use the flutter_snowboy plugin.
version: 0.1.2+1

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audiofileplayer: '^2.1.1'
  path_provider: '^2.0.15'
  audio_session: '^0.1.14'
  flutter_sound: '^9.2.13'

  flutter_snowboy:
    # When depending on this package from a real application you should use:
    #   flutter_snowboy: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/hi_embla.pmdl
    - assets/ding.wav
