name: flutter_snowboy
description: Flutter wrapper plugin for Snowboy hotword detection. Snowboy is a cross-platform DNN-based hotword detection toolkit developed by KITT.AI.
version: 0.1.1+1
homepage: https://github.com/mideind/flutter_snowboy

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        package: is.mideind.flutter_snowboy
        pluginClass: FlutterSnowboyPlugin
      ios:
        pluginClass: FlutterSnowboyPlugin
